- name: Find the version of RPM installed for TSM steps
  shell: 'rpm -qa | grep tableau-server'
  register: tab_rpm

- name: Create local temporary os user {{ temp_os_user }}
  user:
    name: "{{ temp_os_user }}"
    groups: "{{ tableau_secondary_group }}"
    password: "{{ temp_os_user_passwd }}"
    home: /opt/{{ temp_os_user }} 
    state: present

- name: Initialize TSM for tableau server
  shell: sudo  {{ tableau_prefix_dir }}/packages/scripts.{{ tab_rpm.stdout.split('-')[2] }}/initialize-tsm --accepteula -d {{ tableau_prefix_dir }}
  args:
    creates: "{{ tableau_prefix_dir }}/data/tabsvc"
  become: yes
  become_user: "{{ tableau_owner }}"
  become_method: sudo
