


- name: Create directory tableau for tuned profile for user tableau
  file:
    path: /etc/tuned/tableau
    state: directory
    mode: 744
    owner: root
    group: root
    force: no

- name: Deploy the tuned profile for tableau build from template
  template:
    dest: /etc/tuned/tableau/tuned.conf
    src: tuned.conf.j2
    mode: 0644
    owner: root
    group: root
    force: no

- name: Activate the tableau tuned profile
  command: tuned-adm profile tableau


- name: Install dependent OS packages for Tableau Server Installation
  yum:
    name:
      - bash.x86_64
      - bash-completion.noarch
      - chrpath.x86_64
      - fontconfig.x86_64
      - fontconfig.i686
      - freeglut.x86_64
      - freeglut.i686
      - freetype.x86_64
      - freetype.i686
      - fuse.x86_64
      - fuse-libs.x86_64
      - fuse-libs.i686
      - gdb.x86_64
      - krb5-libs.x86_64
      - krb5-libs.i686
      - libXcomposite.x86_64
      - libXcomposite.i686
      - libXcursor.x86_64
      - libXcursor.i686
      - libXi.x86_64
      - libXi.i686
      - libXrandr.x86_64
      - libXrandr.i686
      - libXrender.x86_64
      - libXrender.i686
      - libXtst.x86_64
      - libXtst.i686
      - libxslt.x86_64
      - libxslt.i686
      - mesa-libEGL.x86_64
      - mesa-libEGL.i686
      - net-tools.x86_64
      - redhat-lsb-core.x86_64
      - redhat-lsb-core.i686
      - iotop
      - ksh.x86_64
      - sysstat.x86_64
      - numactl.x86_64
      - numactl-devel.x86_64
      - unzip.x86_64
      - zip.x86_64
      - lvm2.x86_64
    update_cache: yes
    state: present

- name: Create tableau OS user group on the server
  group:
    name: tableau
    state: present
    gid: 10001

- name: Create tsmadmin OS user group on the server
  group:
    name: tsmadmin 
    state: present
    gid: 10002
 
- name: Create tableau OS user on the server
  user:
    name: tableau
    comment: os user for tableau server binaries
    uid: 20001
    group: tableau
    groups: tableau,tsmadmin
    createhome: no
    state: present
    home: /opt/tableau 
    shell: /bin/ksh 

- name: Create home directory for tableau user
  file:
    path: /opt/tableau
    state: directory
    owner: tableau
    group: tableau
    mode: 0750

- name: Apply the user shell limits for operating system user tableau
  copy:
    src: tableau_limits.conf
    dest: /etc/security/limits.d/29-tableau.conf
    mode: 0644


- name: Create the physical volume for tableau software
  lvg:
    vg: tableau_vg
    pvs: "/dev/xvdf"
    state: present

- name: Create the logical volume from physical volume 
  lvol:
    vg: tableau_vg
    lv: tableaubinlv
    size: 19G

- name: Create XFS Filesystem on logical volumes
  filesystem:
    dev: "/dev/mapper/tableau_vg-tableaubinlv"
    fstype: xfs

- name: Mount the XFS filesystem on logical volume
  mount:
    src: "/dev/mapper/tableau_vg-tableaubinlv"
    name: /tableau
    fstype: xfs
    state: mounted

- name: Change the permissions and ownership of directories to tableau user
  file:
    state: directory
    path: /tableau
    owner: tableau
    group: tableau
    mode: 0770
